# Generated by Django 2.2.7 on 2019-11-09 10:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_produit_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='familly',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=8),
        ),
    ]
