# Generated by Django 2.2.7 on 2019-11-09 10:43

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20191109_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True),
        ),
    ]
