# Generated by Django 2.2.7 on 2019-11-09 10:48

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='periode_promo',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
        ),
    ]
